name = "vehicle-entry-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = [ "nodejs_compat" ]

[vars]
SUPABASE_URL = "https://kibguhgpkrdxarvdmiwi.supabase.co"

# Secrets (Add these via: wrangler secret put <NAME>)
# SUPABASE_SERVICE_ROLE_KEY
# JWT_SECRET
# DB_USER
# DB_HOST
# DB_NAME
# DB_PASSWORD
# DB_PORT
